WebAppVinyl/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebAppVinyl.Models
{
    public class Cart
    {
        public int Id { get; set; }
        //[Key]
        //[Column(Order = 1)]
        public int VinylId { get; set; }

        //[Key]
        //[Column(Order = 2)]
        public string BuyerId { get; set; }

        // navigation properties
        public Vinyl Vinyl { get; set; }
        public ApplicationUser Buyer { get; set; }

        public int? Quantity { get; set; }
        
    }
}

WebAppVinyl/Controllers/CartsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using WebAppVinyl.Models;

namespace WebAppVinyl.Controllers
{
    public class CartsController : Controller
    {

        private ApplicationDbContext context;

        public CartsController()
        {
            context = new ApplicationDbContext();
        }


        // GET: Carts
        public ActionResult Index()
        {
            var vinyls = context.Carts
            .Include(c => c.Vinyl.Genre)
            .Include(c => c.Vinyl.Label)
            .ToList();

            return View(vinyls);
        }


        public ActionResult Delete(int id)
        {
            var userId = User.Identity.GetUserId();

            var vinylNotWanted = context.Carts
                .Where(c => c.VinylId == id && c.BuyerId == userId)
                .SingleOrDefault();

            context.Carts.Remove(vinylNotWanted);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

WebAppVinyl/Controllers/api/CartsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using WebAppVinyl.Dtos;
using WebAppVinyl.Models;

namespace WebAppVinyl.Controllers.api
{
    public class CartsController : ApiController
    {
        private ApplicationDbContext context;

        public CartsController()
        {
            context = new ApplicationDbContext();
        }


        [HttpPost]
        public IHttpActionResult Cart(CartDto dto)
        {
            //what if attendance already exist??
            var userId = User.Identity.GetUserId();
            //var exists = context.Attendances.Any(a => a.AttendeeId == userId && a.GigId == gigId);
            if (context.Carts.Any(c => c.BuyerId == userId && c.VinylId == dto.VinylId))
                return BadRequest("Cart already exists");

            var cart = new Cart
            {
                VinylId = dto.VinylId,
                BuyerId = userId
                //Quantity = dto.Vinyl.Quantity

            };
            //add object to attendances DbSet

            context.Carts.Add(cart);
            //save changes to db
            context.SaveChanges();
            
            return Ok();
        }

        [HttpDelete]
        public void DeleteFromCart(int id)
        {
            var userId = User.Identity.GetUserId();

            var vinylNotWanted = context.Carts
                .Where(c => c.VinylId == id && c.BuyerId == userId)
                .SingleOrDefault();

            context.Carts.Remove(vinylNotWanted);
            context.SaveChanges();
            
        }
    }
}

WebAppVinyl/Views/Carts/Index.cshtml
@model IEnumerable<WebAppVinyl.Models.Cart>
@{
    ViewBag.Title = "Index";
}

<h2>My Cart</h2>

<table id="vinyls" class="table table-bordered table-hover">
    <ul>
        @foreach (var vinyl in Model)
        {
            <li>
                <div>
                    <div>@vinyl.Vinyl.Title</div>
                    <div>@vinyl.Vinyl.Artist</div>
                    <div>@vinyl.Vinyl.ReleaseYear</div>
                    <div>@vinyl.Vinyl.Label.Name</div>
                    <div>@vinyl.Vinyl.Genre.Name</div>
                    <div>@vinyl.Vinyl.Price  $</div>

                    <div>@Html.ActionLink("How Many Items", "CreateSummary", "Carts", new { id = vinyl.Vinyl.Id }, null)</div>
                    @*<span data-vinyl-id="@vinyl.Vinyl.Id" class="btn btn-default btn-sm pull-right js-toggle-cart">
                        @Html.ActionLink("Remove From Cart", "Delete", "Carts", new { id = vinyl.Vinyl.Id }, null)
                    </span>*@
                </div>
            </li>
        }
    </ul>
</table>